### ISSUE TITLE
Codeception update to include Dotenv 3.0 breaks wp-browser

### ISSUE THREAD

**Issue by defunctl** [lucatume/wp-browser#210]
This pull appears to have broken running codeception due to wp-browser requiring the 2.4 release: https://github.com/Codeception/Codeception/pull/5327

```
PHP Fatal error:  Uncaught Error: Call to undefined method Dotenv\Dotenv::create() in /application/www/dev/tests/vendor/codeception/codeception/src/Codeception/Lib/ParamsLoader.php:118
Stack trace:
#0 /application/www/dev/tests/vendor/codeception/codeception/src/Codeception/Lib/ParamsLoader.php(44): Codeception\Lib\ParamsLoader->loadDotEnvFile()
#1 /application/www/dev/tests/vendor/codeception/codeception/src/Codeception/Configuration.php(771): Codeception\Lib\ParamsLoader->load('.env')
#2 /application/www/dev/tests/vendor/codeception/codeception/src/Codeception/Configuration.php(178): Codeception\Configuration::prepareParams(Array)
#3 /application/www/dev/tests/vendor/codeception/codeception/src/Codeception/Application.php(55): Codeception\Configuration::config()
#4 /application/www/dev/tests/vendor/codeception/codeception/src/Codeception/Application.php(33): Codeception\Application->readCustomCommandsFromConfig()
#5 /application/www/dev/tests/vendor/codeception/codeception/codecept(42): Codeception\Application->registerCusto in /application/www/dev/tests/vendor/codeception/codeception/src/Codeception/Lib/ParamsLoader.php on line 118
```

**Comment by defunctl** [comment]
And https://github.com/Codeception/Codeception/pull/5366

**Comment by defunctl** [comment]
Current workaround is to first include codeception 2.5.2 before wp-browser in your composer.json

```
    "require-dev": {
        "codeception/codeception": "2.5.2",
        "lucatume/wp-browser": "^2.2",
    },
```

**Comment by khaiknievel** [comment]
And also two specific version of the following packages.

```json
"require-dev": {
  "codeception/phpunit-wrapper": "^6.0.9",
  "phpunit/phpunit": "6.*"
}
```

**Comment by Naktibalda** [comment]
@khaiknievel wp-browser and Codeception are compatible with PhpUnit 7: https://travis-ci.org/lucatume/wp-browser/jobs/482053920

Probably you have to update your tests to make them compatible with PhpUnit 7.

**Comment by khaiknievel** [comment]
Your are right. Did a separate clean setup and all is good. Yurp, my tests code is bad.

**Comment by lucatume** [comment]
Thanks @Naktibalda for the PR, very much appreciated.
Thanks @khaiknievel for reporting the issue, again: very much appreciated.
